name: skillapp
description: A new Flutter project.

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" # Matches Dart version compatibility

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 # For iOS-style icons
  http: ^1.2.2 # HTTP package for API calls
  mongo_dart: ^0.10.0 # MongoDB package for direct database interaction
  bcrypt: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Linting rules for Flutter

flutter:
  uses-material-design: true # Enables Material Design icons and themes
